version: '3.9'
services:
  chatbot:
    container_name: chatbot
    build: .
    restart: always
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    ports:
      - "8001:8001"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    networks:
      - db

networks:
  db:
    driver: bridge