version: '3.9'
services:
  chatbot:
    container_name: chatbot
    build: .
    restart: always
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    ports:
      - "8001:8001"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [ gpu ]
    networks:
      - db
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.26.10-community
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/localgpt123
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
    networks:
      - db

networks:
  db:
    driver: bridge